### ISSUE TITLE
Minor Apostrophee issue in some code

### ISSUE THREAD

**Issue by Kamrulhasan12345** [rutura/Qt6QMLBeginnersBookRelease#1]
Hi,
It would be helpful for me to know if there should be two repeated apostrophes at the last in page-39 code.

![image](https://github.com/rutura/Qt6QMLBeginnersBookRelease/assets/32530625/926508df-69d2-4f91-b95f-2c10c1e04d45)

Thanks in advance!

**Comment by Colins2** [comment]
I don't have that in my copy?

**Comment by Kamrulhasan12345** [comment]
After rethinking, I think I should close this, as this isn't a major issue at all.
