### ISSUE TITLE
Font used for code is difficult to read

### ISSUE THREAD

**Issue by koansoftware** [rutura/Qt6QMLBeginnersBookRelease#2]
Font used for code is difficult to read, in particular the ampersand character '&'.
You should consider not only dyslexics but non-Western readers as well , therefore the 'g' can be easily confused with 'q'.

**Comment by rutura** [comment]
Hello @koansoftware . Can you please share a a screenshot of how the '&' looks on your end? That way I know exactly what I am trying to work around. 

Regards,
Daniel.

**Comment by koansoftware** [comment]
> Hello @koansoftware . Can you please share a a screenshot of how the '&' looks on your end? That way I know exactly what I am trying to work around.
> 
> Regards, Daniel.


Hi @rutura Daniel,
I simply downloaded the [link to the PDF](https://github.com/rutura/Qt6QMLBeginnersBookRelease/releases/download/v0.0.1/Qt6QMLForBeginners_1stEdition_Daniel_Gakwaya.pdf) from the README.md in this repo.

However, this is a screenshot from page #23

![Screenshot from 2023-05-30 11-22-52](https://github.com/rutura/Qt6QMLBeginnersBookRelease/assets/1222942/462d62ae-f5ba-402b-97d1-08e59d0662ff)


Just my two cents ;-)

Marco

**Comment by rutura** [comment]
Yes. Now I see that the & symbol is a problem. I'll play with the fonts and see what works better.

Thanks for bringing this up.

Daniel.
