### ISSUE TITLE
A section about interfacing with C++

### ISSUE THREAD

**Issue by DavidLazarescu** [rutura/Qt6QMLBeginnersBookRelease#3]
Hey, I have looked through the book and it seems very decent. I know that this book should focus on Qml (as your courses do), but non-the-less I think that a section on interfacing to C++ would be a great addition to it.

Most Qt developers are using C++ and it is quite confusing to figure this part our by yourself (Or at least it was for me when I learned Qml). An overview on how to do it would definitely make this book seem more useful in real-life scenarios, since pretty much every real Qml application will need to connect to a C++ (or potentially python) backend.

**Comment by rutura** [comment]
Hello @DavidLazarescu .
Thanks for the feedback. I wanted to cover at least the basics of interfacing to C++ but then I got stuck to whether or not to cover python as well. It's not there yet, but you can do a lot already in terms of interfacing to QML. Then I decided to make this book purely about a QML frontend and later on have separate books on "Interfacing to C++" and "Interfacing to Python".  May be I should cover the basics and refer the readers to these specific books for more. Let me know what you think.

Daniel.

**Comment by DavidLazarescu** [comment]
Imo. at least interfacing to c++ should be covered in the book, since most QML users are c++ users. Python would also be nice to cover, but if time is a problem, you could wait with it and see how big the request for it is.

Leaving the reader without any content on interfacing with c++ will leave most of the readers of the book helpless though.

I think a relatively simple chapter, covering the basics of interfacing with C++ should suffice.
I think at least things like the Qml engine, Registering Types, macros like Q_INVOKABLE and QProperties should be explained.

Also, I am not sure how useful it would be to have extra books on "Interfacing to Python" and "Interfacing to C++". I don't think there is enough content to fill a whole book on just this (maybe I am very wrong and I am missing a lot of knowledge on this subject, but I don't think so).
On the other hand, I think it would be quite interesting to have  a deep dive book on Qt and Qml where things like the MOC, including its details, the API and the inner workings of the QmlEngine, ..., would be discussed. This would also be a book where you cloud go into more detail about interfacing to c++.

David.

**Comment by rutura** [comment]
I'll plan a chapter with the basics on interfacing to C++ and adjust based on the reception. Thanks for bringing this up.
