### ISSUE TITLE
Just a typo 

### ISSUE THREAD

**Issue by johnspeny** [rutura/Qt6QMLBeginnersBookRelease#4]
![Screenshot_20230610-224855_Adobe Acrobat](https://github.com/rutura/Qt6QMLBeginnersBookRelease/assets/30299284/8ff51180-d437-4e1f-8135-ffdfec3ec2b2)

Change tpye to type in the sample code. I discovered it while reading through. Thanks for the great content so far.

**Comment by rutura** [comment]
Fixed.
