### ISSUE TITLE
Inconsistent punctuation

### ISSUE THREAD

**Issue by rbo-ktw** [rutura/Qt6QMLBeginnersBookRelease#6]
I see chaos in the punctuation. Both in text and code. For example, sometimes there is no space after the period:

===

![obraz](https://github.com/rutura/Qt6QMLBeginnersBookRelease/assets/43962167/70320df6-1e83-4f1d-b08a-3aab0b6dd5a1)

===

![obraz](https://github.com/rutura/Qt6QMLBeginnersBookRelease/assets/43962167/f8d8c14e-52ba-4a1a-8c97-94f19722c973)

===

You can use (on Linux) the command:
`pdfgrep "\w\.[A-Z]" Qt6QMLForBeginners_1stEdition_Daniel_Gakwaya.pdf`
to find all occurrences of this problem. This will of course also find some false positives, but it will still speed up the identification of instances of this error.

In many code listings, you randomly put a space before the colon/semicolon in parameter declarations. Sometimes there is no space after colon/semicolon. See e.g. page 74: 

===

![obraz](https://github.com/rutura/Qt6QMLBeginnersBookRelease/assets/43962167/d22cd483-0943-48d0-ac25-26e1ec34bdb8)

===

To find all occurrences of missing space after colon/semicolon:
`pdfgrep -P "[^:][:;][^\s/\\:\d]" Qt6QMLForBeginners_1stEdition_Daniel_Gakwaya.pdf`

To find all occurrences of unnecessary space before colon/semicolon/comma:
`pdfgrep -P "\s[:;,]" Qt6QMLForBeginners_1stEdition_Daniel_Gakwaya.pdf`

**Comment by rutura** [comment]
Thanks for bringing this up @rbo-ktw . I went through the book fixing all these spacing and style issues. Credit goes to Tom Betka, the technical editor, for tirelessly going through the book hunting these down.
