### ISSUE TITLE
Qt.Include is deprecated

### ISSUE THREAD

**Issue by rbo-ktw** [rutura/Qt6QMLBeginnersBookRelease#7]
According to [doc.qt.io](https://doc.qt.io/qt-6/qtqml-javascript-imports.html#importing-a-javascript-resource-from-another-javascript-resource):

> The Qt.include() function includes one JavaScript file from another without using ECMAScript modules and without qualifying the import. It makes all functions and variables from the other file available in the current file's namespace, but ignores all pragmas and imports defined in that file. **This is not a good idea** as a function call should never modify the caller's context.

> Qt.include() **is deprecated and should be avoided. It will be removed in a future version of Qt.**

That is why you should remove the chapter describing Qt.include() from your book and focus on the ECMAScript syntax.

**Comment by rutura** [comment]
Thanks for bringing this up @rbo-ktw . The facility is still used in QML code out there. I thought that I should inform readers about it, but still inform them that they should avoid it in new QML projects.
